package database

import (
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5/pgconn"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
)

// ============================================================
// 1. CONNECT TO POSTGRESQL
//
// Responsibility:
// - Load DATABASE_URL.
// - Connect Agro-Shield to PostgreSQL.
// - Verify that the database is reachable.
// ============================================================

func ConnectDB() (*sql.DB, error) {

	godotenv.Load()

	databaseURL := os.Getenv("DATABASE_URL")

	if databaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is not set")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(); err != nil {
		return nil, err
	}

	log.Println("✅ Connected to PostgreSQL database")

	return db, nil
}

// ============================================================
// 2. RUN DATABASE MIGRATIONS
//
// Responsibility:
// - Create all Agro-Shield database tables.
// - Update older tables when new columns are introduced.
// ============================================================

func RunMigration(db *sql.DB) error {
	marketEventsTable := `
	CREATE TABLE IF NOT EXISTS market_events (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		event_type TEXT NOT NULL,
		crop_id INTEGER,
		user_id INTEGER,
		session_id TEXT,
		metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT fk_market_events_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
		CONSTRAINT fk_market_events_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
	);
	CREATE INDEX IF NOT EXISTS idx_market_events_crop_time ON market_events(crop_id, created_at);
	CREATE INDEX IF NOT EXISTS idx_market_events_type_time ON market_events(event_type, created_at);
	`
	marketplaceSearchesTable := `
	CREATE TABLE IF NOT EXISTS marketplace_searches (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		search_term TEXT NOT NULL,
		normalized_produce TEXT,
		location TEXT,
		user_id INTEGER,
		session_id TEXT,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT fk_marketplace_searches_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
	);
	CREATE INDEX IF NOT EXISTS idx_marketplace_searches_term_time ON marketplace_searches(normalized_produce, created_at);
	CREATE INDEX IF NOT EXISTS idx_marketplace_searches_location_time ON marketplace_searches(location, created_at);
	`
	historyTables := `
	ALTER TABLE farmers ADD COLUMN IF NOT EXISTS lga TEXT;
	ALTER TABLE farmers ADD COLUMN IF NOT EXISTS state TEXT;
	ALTER TABLE farmers ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Nigeria';
	ALTER TABLE crops ADD COLUMN IF NOT EXISTS lga TEXT;
	ALTER TABLE crops ADD COLUMN IF NOT EXISTS state TEXT;
	ALTER TABLE crops ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Nigeria';
	CREATE TABLE IF NOT EXISTS produce_price_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, crop_id INTEGER NOT NULL REFERENCES crops(id) ON DELETE CASCADE, price_per_unit DOUBLE PRECISION NOT NULL, unit TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'Agro-Shield', observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
	CREATE INDEX IF NOT EXISTS idx_price_history_crop_time ON produce_price_history(crop_id, observed_at);
	CREATE TABLE IF NOT EXISTS inventory_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, crop_id INTEGER NOT NULL REFERENCES crops(id) ON DELETE CASCADE, quantity_before DOUBLE PRECISION NOT NULL, quantity_change DOUBLE PRECISION NOT NULL, quantity_after DOUBLE PRECISION NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
	CREATE INDEX IF NOT EXISTS idx_inventory_history_crop_time ON inventory_history(crop_id, created_at);
	UPDATE farmers SET lga=location WHERE lga IS NULL OR BTRIM(lga)='';
	UPDATE farmers SET state='Benue' WHERE state IS NULL OR BTRIM(state)='';
	UPDATE farmers SET country='Nigeria' WHERE country IS NULL OR BTRIM(country)='';
	UPDATE crops SET lga=location WHERE lga IS NULL OR BTRIM(lga)='';
	UPDATE crops SET state=COALESCE((SELECT state FROM farmers WHERE farmers.id=crops.farmer_id),'Benue') WHERE state IS NULL OR BTRIM(state)='';
	UPDATE crops SET country='Nigeria' WHERE country IS NULL OR BTRIM(country)='';
	CREATE TABLE IF NOT EXISTS external_market_prices (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, produce_type TEXT NOT NULL, price_per_unit DOUBLE PRECISION NOT NULL, unit TEXT NOT NULL, currency TEXT NOT NULL DEFAULT 'NGN', provider TEXT NOT NULL, market_name TEXT NOT NULL, lga TEXT, state TEXT, country TEXT NOT NULL DEFAULT 'Nigeria', collected_at TIMESTAMP NOT NULL, imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, source_url TEXT);
	CREATE INDEX IF NOT EXISTS idx_external_prices_produce_market_time ON external_market_prices(produce_type, state, collected_at);
	CREATE TABLE IF NOT EXISTS lga_neighbors (state TEXT NOT NULL, lga TEXT NOT NULL, neighbor_lga TEXT NOT NULL, PRIMARY KEY(state,lga,neighbor_lga));
	`

	// ========================================================
	// 3. FARMERS TABLE
	//
	// Stores all Agro-Shield users.
	// ========================================================

	farmersTable := `
	CREATE TABLE IF NOT EXISTS farmers (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		full_name TEXT NOT NULL,

		phone TEXT NOT NULL UNIQUE,

		email TEXT,

		password_hash TEXT NOT NULL,

		location TEXT NOT NULL,

		role TEXT NOT NULL DEFAULT 'farmer',

		photo_url TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);
	`

	_, err := db.Exec(farmersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers table migrated successfully")

	// ========================================================
	// 4. FARMERS EMAIL COLUMN MIGRATION
	//
	// Makes sure older databases also receive email.
	// ========================================================

	addEmailColumn := `
	ALTER TABLE farmers
	ADD COLUMN IF NOT EXISTS email TEXT;
	`

	_, err = db.Exec(addEmailColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers email column migrated successfully")

	// Backfill legacy rows before enforcing the required media columns.
	if _, err = db.Exec(`UPDATE farmers SET photo_url = '/static/assets/images/un.jpeg' WHERE photo_url IS NULL OR BTRIM(photo_url) = ''`); err != nil {
		return fmt.Errorf("farmers.photo_url backfill failed: %w", err)
	}
	if _, err = db.Exec(`ALTER TABLE farmers ALTER COLUMN photo_url DROP DEFAULT; ALTER TABLE farmers ALTER COLUMN photo_url SET NOT NULL; ALTER TABLE farmers DROP CONSTRAINT IF EXISTS farmers_photo_url_nonblank; ALTER TABLE farmers ADD CONSTRAINT farmers_photo_url_nonblank CHECK (BTRIM(photo_url) <> '')`); err != nil {
		return fmt.Errorf("farmers.photo_url must be populated before migration: %w", err)
	}

	// ========================================================
	// 5. CROPS TABLE
	//
	// Stores agricultural produce listed by farmers.
	// ========================================================

	cropsTable := `
	CREATE TABLE IF NOT EXISTS crops (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		farmer_id INTEGER NOT NULL,

		name TEXT NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		unit TEXT NOT NULL,

		location TEXT NOT NULL,

		price_per_unit DOUBLE PRECISION NOT NULL,

		listed_for_sale BOOLEAN NOT NULL DEFAULT FALSE,

		image_url TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_crops_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(cropsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Crops table migrated successfully")

	// ========================================================
// 5B. CROP IMAGES TABLE
//
// Stores one or more images belonging to a crop/product.
//
// A crop must have at least one image when created.
// Additional images are allowed.
// ========================================================

cropImagesTable := `
CREATE TABLE IF NOT EXISTS crop_images (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	crop_id INTEGER NOT NULL,

	image_url TEXT NOT NULL,

	is_primary BOOLEAN NOT NULL DEFAULT FALSE,

	sort_order INTEGER NOT NULL DEFAULT 0,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_crop_images_crop
		FOREIGN KEY (crop_id)
		REFERENCES crops(id)
		ON DELETE CASCADE,

	CONSTRAINT chk_crop_images_url
		CHECK (BTRIM(image_url) <> '')
);

CREATE INDEX IF NOT EXISTS idx_crop_images_crop_id
	ON crop_images(crop_id);

CREATE INDEX IF NOT EXISTS idx_crop_images_crop_sort
	ON crop_images(crop_id, sort_order);
`

if _, err = db.Exec(cropImagesTable); err != nil {
	return err
}

log.Println("✅ Crop images table migrated successfully")
	lifecycleColumns := `ALTER TABLE crops ADD COLUMN IF NOT EXISTS initial_listed_quantity DOUBLE PRECISION; ALTER TABLE crops ADD COLUMN IF NOT EXISTS first_listed_at TIMESTAMP; ALTER TABLE crops ADD COLUMN IF NOT EXISTS first_order_at TIMESTAMP; ALTER TABLE crops ADD COLUMN IF NOT EXISTS sold_out_at TIMESTAMP; UPDATE crops SET initial_listed_quantity=quantity WHERE initial_listed_quantity IS NULL; UPDATE crops SET first_listed_at=created_at WHERE first_listed_at IS NULL AND listed_for_sale=true;`
	if _, err = db.Exec(lifecycleColumns); err != nil {
		return err
	}
	log.Println("✅ Produce listing lifecycle columns migrated successfully")
	if _, err = db.Exec(`ALTER TABLE crops ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION; ALTER TABLE crops ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION; ALTER TABLE crops ADD COLUMN IF NOT EXISTS location_accuracy DOUBLE PRECISION;`); err != nil {
		return err
	}

	if _, err = db.Exec(marketEventsTable); err != nil {
		return err
	}
	log.Println("✅ Market events table migrated successfully")
	if _, err = db.Exec(marketplaceSearchesTable); err != nil {
		return err
	}
	if _, err = db.Exec(historyTables); err != nil {
		return err
	}
	log.Println("✅ Marketplace searches table migrated successfully")

	if _, err = db.Exec(`UPDATE crops SET image_url = '/static/assets/images/un.jpeg' WHERE image_url IS NULL OR BTRIM(image_url) = ''`); err != nil {
		return fmt.Errorf("crops.image_url backfill failed: %w", err)
	}
	if _, err = db.Exec(`ALTER TABLE crops ALTER COLUMN image_url DROP DEFAULT; ALTER TABLE crops ALTER COLUMN image_url SET NOT NULL; ALTER TABLE crops DROP CONSTRAINT IF EXISTS crops_image_url_nonblank; ALTER TABLE crops ADD CONSTRAINT crops_image_url_nonblank CHECK (BTRIM(image_url) <> '')`); err != nil {
		return fmt.Errorf("crops.image_url must be populated before migration: %w", err)
	}

	// ========================================================
	// 6. DIAGNOSES TABLE
	//
	// Stores AI diagnosis results.
	// ========================================================

	diagnosesTable := `
	CREATE TABLE IF NOT EXISTS diagnoses (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	farmer_id INTEGER NOT NULL,

	category TEXT NOT NULL DEFAULT '',

	description TEXT NOT NULL DEFAULT '',

	result TEXT NOT NULL,

	image_name TEXT,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_diagnoses_farmer
		FOREIGN KEY (farmer_id)
		REFERENCES farmers(id)
		ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnoses table migrated successfully")

	// ========================================================
	// 7. DIAGNOSIS MEDIA TABLE
	//
	// Stores media connected to AI diagnoses.
	// ========================================================

	diagnosisCompatibilityMigration := `
	        ALTER TABLE diagnoses
	                ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
	
	        ALTER TABLE diagnoses
	                ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
	
	        ALTER TABLE diagnoses
	                ADD COLUMN IF NOT EXISTS image_name TEXT;
	
	        ALTER TABLE diagnoses
	                ALTER COLUMN image_name DROP NOT NULL;
	        `

	if _, err = db.Exec(diagnosisCompatibilityMigration); err != nil {
		return fmt.Errorf(
			"diagnoses compatibility migration failed: %w",
			err,
		)
	}

	log.Println("✅ Diagnoses compatibility migration completed")

	diagnosisMediaTable := `
	CREATE TABLE IF NOT EXISTS diagnosis_media (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		diagnosis_id INTEGER NOT NULL,

		media_type TEXT NOT NULL,

		file_name TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnosis_media_diagnosis
			FOREIGN KEY (diagnosis_id)
			REFERENCES diagnoses(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosisMediaTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnosis media table migrated successfully")

	// ========================================================
	// 8. ORDERS TABLE
	//
	// Stores purchases made by buyers.
	// ========================================================

	ordersTable := `
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		buyer_id INTEGER NOT NULL,

		crop_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		total_price DOUBLE PRECISION NOT NULL,

		status TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_orders_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_orders_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id)
	);
	`

	_, err = db.Exec(ordersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Orders table migrated successfully")

	// ========================================================
	// 9. NEGOTIATIONS TABLE
	//
	// Stores buyer ↔ farmer negotiations.
	// ========================================================

	negotiationsTable := `
	CREATE TABLE IF NOT EXISTS negotiations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		crop_id INTEGER NOT NULL,

		buyer_id INTEGER NOT NULL,

		farmer_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		status TEXT NOT NULL,

		round_count INTEGER NOT NULL DEFAULT 0,

		max_rounds INTEGER NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		expires_at TIMESTAMP,

		CONSTRAINT fk_negotiations_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_negotiations_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_negotiations_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
	);
	`

	_, err = db.Exec(negotiationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiations table migrated successfully")

	// ========================================================
	// 10. NEGOTIATION MESSAGES TABLE
	//
	// Stores messages and offers inside negotiations.
	//
	// This is DIFFERENT from general chat.
	// ========================================================

	negotiationMessagesTable := `
	CREATE TABLE IF NOT EXISTS negotiation_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		negotiation_id INTEGER NOT NULL,

		sender_id INTEGER NOT NULL,

		message_type TEXT NOT NULL DEFAULT 'offer',

		offer_price DOUBLE PRECISION NOT NULL DEFAULT 0,

		message TEXT NOT NULL DEFAULT '',

		offer_status TEXT NOT NULL DEFAULT 'pending',

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_messages_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id),

		CONSTRAINT chk_message_type
			CHECK (message_type IN ('message', 'offer')),

		CONSTRAINT chk_offer_status
			CHECK (
				offer_status IN (
					'none',
					'pending',
					'accepted',
					'rejected'
				)
			)
	);
	`

	_, err = db.Exec(negotiationMessagesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation messages table migrated successfully")

	// ========================================================
	// 10B. NEGOTIATION MESSAGE TYPE MIGRATION
	//
	// Adds message_type to older databases.
	// ========================================================

	addMessageTypeColumn := `
	ALTER TABLE negotiation_messages
	ADD COLUMN IF NOT EXISTS message_type TEXT NOT NULL DEFAULT 'offer';
	`

	_, err = db.Exec(addMessageTypeColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation message type column migrated successfully")

	// ========================================================
	// 10C. NEGOTIATION OFFER STATUS MIGRATION
	//
	// Adds offer_status to older databases.
	// ========================================================

	addOfferStatusColumn := `
	ALTER TABLE negotiation_messages
	ADD COLUMN IF NOT EXISTS offer_status TEXT NOT NULL DEFAULT 'pending';
	`

	_, err = db.Exec(addOfferStatusColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation offer status column migrated successfully")

	// ========================================================
	// 11. CART ITEMS TABLE
	//
	// Stores accepted negotiation deals before checkout.
	// ========================================================

	cartItemsTable := `
	CREATE TABLE IF NOT EXISTS cart_items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		buyer_id INTEGER NOT NULL,

		crop_id INTEGER NOT NULL,

		negotiation_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		price_per_unit DOUBLE PRECISION NOT NULL,

		total_price DOUBLE PRECISION NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_cart_items_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_cart_items_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_cart_items_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT chk_cart_items_quantity
			CHECK (quantity > 0),

		CONSTRAINT chk_cart_items_price
			CHECK (price_per_unit > 0),

		CONSTRAINT chk_cart_items_total
			CHECK (total_price > 0)
	);
	`

	_, err = db.Exec(cartItemsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Cart items table migrated successfully")

	// ========================================================
	// 12. NOTIFICATIONS TABLE
	//
	// Stores notifications for Agro-Shield users.
	// ========================================================

	notificationsTable := `
	CREATE TABLE IF NOT EXISTS notifications (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		user_id INTEGER NOT NULL,

		title TEXT NOT NULL,

		message TEXT NOT NULL,

		type TEXT NOT NULL,

		is_read BOOLEAN NOT NULL DEFAULT FALSE,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_notifications_user
			FOREIGN KEY (user_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(notificationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Notifications table migrated successfully")

	// ========================================================
	// 13. CONVERSATIONS TABLE
	//
	// Represents a general Agro-Shield chat room.
	//
	// private:
	//   User ↔ User
	//
	// group:
	//   User ↔ User ↔ User ↔ ...
	//
	// IMPORTANT:
	// This is NOT a negotiation.
	// ========================================================

	conversationsTable := `
	CREATE TABLE IF NOT EXISTS conversations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		name TEXT,

		type TEXT NOT NULL DEFAULT 'private',

		created_by INTEGER NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_conversations_creator
			FOREIGN KEY (created_by)
			REFERENCES farmers(id)
			ON DELETE CASCADE,

		CONSTRAINT chk_conversation_type
			CHECK (type IN ('private', 'group'))
	);
	`

	_, err = db.Exec(conversationsTable)
	if err != nil {
		return err
	}

	// Older deployments may have created conversations without the
	// current name column. Keep the migration additive and idempotent so
	// those databases can be upgraded without dropping chat history.
	if _, err = db.Exec(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS name TEXT;`); err != nil {
		return err
	}
	// Older deployments may also have created conversations before the type
	// column was introduced. Default legacy rows to private conversations so
	// repository queries remain compatible without losing chat history.
	if _, err = db.Exec(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'private';`); err != nil {
		return err
	}
	// created_by was added after the first chat schema shipped. Add it as
	// nullable for now; once conversation_members is available below, legacy
	// rows can be backfilled before the NOT NULL constraint is restored.
	if _, err = db.Exec(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS created_by INTEGER;`); err != nil {
		return err
	}
	// Older deployments may also lack timestamp columns that are selected and
	// maintained by the conversation repository. Add them without replacing
	// existing chat history.
	if _, err = db.Exec(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;`); err != nil {
		return err
	}
	if _, err = db.Exec(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;`); err != nil {
		return err
	}
	// The first chat implementation stored private participants directly on the
	// conversations row. The current model stores every participant in
	// conversation_members so that the same table supports private and group
	// chats. Keep the legacy columns, but make them optional: current inserts do
	// not populate them and group conversations do not have a fixed pair.
	if _, err = db.Exec(`
		ALTER TABLE conversations ALTER COLUMN user_one_id DROP NOT NULL;
		ALTER TABLE conversations ALTER COLUMN user_two_id DROP NOT NULL;
	`); err != nil {
		// Fresh databases do not have the legacy columns. Only ignore PostgreSQL's
		// undefined-column error; every other migration failure must still stop
		// startup.
		var pgErr *pgconn.PgError
		if !errors.As(err, &pgErr) || pgErr.Code != "42703" {
			return fmt.Errorf("legacy conversation columns migration failed: %w", err)
		}
	}

	log.Println("✅ Conversations table migrated successfully")

	// ========================================================
	// 14. CONVERSATION MEMBERS TABLE
	//
	// Connects users to conversations.
	//
	// This table makes group chat possible.
	//
	// Example:
	//
	// Maize Farmers Association
	//        |
	//        +-- James
	//        +-- Peter
	//        +-- Grace
	//        +-- Michael
	// ========================================================

	conversationMembersTable := `
	CREATE TABLE IF NOT EXISTS conversation_members (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		conversation_id INTEGER NOT NULL,

		user_id INTEGER NOT NULL,

		joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_conversation_members_conversation
			FOREIGN KEY (conversation_id)
			REFERENCES conversations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_conversation_members_user
			FOREIGN KEY (user_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE,

		CONSTRAINT unique_conversation_member
			UNIQUE (conversation_id, user_id)
	);
	`

	_, err = db.Exec(conversationMembersTable)
	if err != nil {
		return err
	}
	if _, err = db.Exec(`ALTER TABLE conversation_members ADD COLUMN IF NOT EXISTS last_read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`); err != nil {
		return err
	}

	// Preserve participants from the legacy two-column private-chat schema.
	// Dynamic SQL keeps this migration valid for fresh databases where those
	// columns never existed.
	if _, err = db.Exec(`
		DO $$
		BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.columns
				WHERE table_schema = current_schema()
				  AND table_name = 'conversations'
				  AND column_name = 'user_one_id'
			) THEN
				INSERT INTO conversation_members (conversation_id, user_id)
				SELECT id, user_one_id FROM conversations WHERE user_one_id IS NOT NULL
				ON CONFLICT (conversation_id, user_id) DO NOTHING;
			END IF;

			IF EXISTS (
				SELECT 1 FROM information_schema.columns
				WHERE table_schema = current_schema()
				  AND table_name = 'conversations'
				  AND column_name = 'user_two_id'
			) THEN
				INSERT INTO conversation_members (conversation_id, user_id)
				SELECT id, user_two_id FROM conversations WHERE user_two_id IS NOT NULL
				ON CONFLICT (conversation_id, user_id) DO NOTHING;
			END IF;
		END $$;
	`); err != nil {
		return fmt.Errorf("legacy conversation members migration failed: %w", err)
	}

	// Upgrade conversations created by older deployments. The earliest member
	// is the best available representation of the original creator. Refuse to
	// silently invent a creator for orphaned conversations, since doing so would
	// assign ownership to an unrelated user.
	if _, err = db.Exec(`
		UPDATE conversations c
		SET created_by = (
			SELECT cm.user_id
			FROM conversation_members cm
			WHERE cm.conversation_id = c.id
			ORDER BY cm.joined_at ASC, cm.id ASC
			LIMIT 1
		)
		WHERE c.created_by IS NULL;
	`); err != nil {
		return fmt.Errorf("conversations.created_by backfill failed: %w", err)
	}
	var conversationsWithoutCreator int
	if err = db.QueryRow(`SELECT COUNT(*) FROM conversations WHERE created_by IS NULL`).Scan(&conversationsWithoutCreator); err != nil {
		return err
	}
	if conversationsWithoutCreator > 0 {
		return fmt.Errorf("cannot migrate conversations.created_by: %d conversation(s) have no members", conversationsWithoutCreator)
	}
	if _, err = db.Exec(`
		ALTER TABLE conversations ALTER COLUMN created_by SET NOT NULL;
		DO $$
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM pg_constraint
				WHERE conrelid = 'conversations'::regclass
				  AND conname = 'fk_conversations_creator'
			) THEN
				ALTER TABLE conversations
					ADD CONSTRAINT fk_conversations_creator
					FOREIGN KEY (created_by) REFERENCES farmers(id) ON DELETE CASCADE;
			END IF;
		END $$;
	`); err != nil {
		return fmt.Errorf("conversations.created_by constraint migration failed: %w", err)
	}

	log.Println("✅ Conversation members table migrated successfully")

	// ========================================================
	// 15. CHAT MESSAGES TABLE
	//
	// Stores normal Agro-Shield chat messages.
	//
	// This is different from negotiation_messages.
	// ========================================================

	chatMessagesTable := `
	CREATE TABLE IF NOT EXISTS chat_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		conversation_id INTEGER NOT NULL,

		sender_id INTEGER NOT NULL,

		message TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_chat_messages_conversation
			FOREIGN KEY (conversation_id)
			REFERENCES conversations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_chat_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(chatMessagesTable)
	if err != nil {
		return err
	}

	// Collapse duplicate private threads created by older chat flows. Messages
	// and memberships are moved to the oldest conversation before duplicates
	// are removed, so each pair of users has one continuous history.
	if _, err = db.Exec(`
		WITH private_pairs AS (
			SELECT c.id, MIN(c.id) OVER (PARTITION BY
				(SELECT ARRAY_AGG(cm.user_id ORDER BY cm.user_id)
				 FROM conversation_members cm WHERE cm.conversation_id = c.id)
			) AS canonical_id
			FROM conversations c WHERE c.type = 'private'
		), duplicates AS (
			SELECT id, canonical_id FROM private_pairs WHERE id <> canonical_id
		)
		UPDATE chat_messages m SET conversation_id = d.canonical_id
		FROM duplicates d WHERE m.conversation_id = d.id;

		WITH private_pairs AS (
			SELECT c.id, MIN(c.id) OVER (PARTITION BY
				(SELECT ARRAY_AGG(cm.user_id ORDER BY cm.user_id)
				 FROM conversation_members cm WHERE cm.conversation_id = c.id)
			) AS canonical_id
			FROM conversations c WHERE c.type = 'private'
		)
		INSERT INTO conversation_members (conversation_id, user_id)
		SELECT p.canonical_id, cm.user_id
		FROM private_pairs p JOIN conversation_members cm ON cm.conversation_id = p.id
		WHERE p.id <> p.canonical_id
		ON CONFLICT (conversation_id, user_id) DO NOTHING;

		DELETE FROM conversations c
		USING (
			SELECT id, MIN(id) OVER (PARTITION BY
				(SELECT ARRAY_AGG(cm.user_id ORDER BY cm.user_id)
				 FROM conversation_members cm WHERE cm.conversation_id = c2.id)
			) AS canonical_id
			FROM conversations c2 WHERE c2.type = 'private'
		) d
		WHERE c.id = d.id AND d.id <> d.canonical_id;
	`); err != nil {
		return fmt.Errorf("duplicate private conversation migration failed: %w", err)
	}

	log.Println("✅ Chat messages table migrated successfully")

	// ========================================================
	// 16. DATABASE MIGRATION COMPLETE
	// ========================================================

	log.Println("✅ All database migrations completed successfully")

	return nil
}
