package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
)

// ConnectDB opens the PostgreSQL database configured by DATABASE_URL.
func ConnectDB() (*sql.DB, error) {
	_ = godotenv.Load()

	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is not set")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open PostgreSQL: %w", err)
	}

	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping PostgreSQL: %w", err)
	}

	log.Println("✅ Connected to PostgreSQL database")
	return db, nil
}

// RunMigration creates the complete Agro-Shield schema on a NEW PostgreSQL
// database. This file intentionally does not try to repair legacy schemas.
// Point DATABASE_URL at a fresh Neon database and run the application once.
func RunMigration(db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("database connection is nil")
	}

	// -------------------------------------------------------------------------
	// 1. USERS / FARMERS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS farmers (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_name TEXT NOT NULL,
	phone TEXT NOT NULL UNIQUE,
	email TEXT,
	password_hash TEXT NOT NULL,
	location TEXT NOT NULL,
	lga TEXT,
	state TEXT,
	country TEXT NOT NULL DEFAULT 'Nigeria',
	role TEXT NOT NULL DEFAULT 'farmer',
	photo_url TEXT NOT NULL DEFAULT '/static/assets/images/un.jpeg',
	bank_name TEXT,
	account_name TEXT,
	account_number VARCHAR(10),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT farmers_photo_url_nonblank CHECK (BTRIM(photo_url) <> ''),
	CONSTRAINT farmers_account_number_valid CHECK (account_number IS NULL OR account_number = '' OR account_number ~ '^[0-9]{10}$')
);
CREATE INDEX IF NOT EXISTS idx_farmers_role ON farmers(role);
CREATE INDEX IF NOT EXISTS idx_farmers_state_lga ON farmers(state, lga);
`); err != nil {
		return fmt.Errorf("farmers migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 2. CROPS / MARKETPLACE PRODUCTS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS crops (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	farmer_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	quantity DOUBLE PRECISION NOT NULL,
	unit TEXT NOT NULL,
	location TEXT NOT NULL,
	lga TEXT,
	state TEXT,
	country TEXT NOT NULL DEFAULT 'Nigeria',
	latitude DOUBLE PRECISION,
	longitude DOUBLE PRECISION,
	location_accuracy DOUBLE PRECISION,
	price_per_unit DOUBLE PRECISION NOT NULL,
	listed_for_sale BOOLEAN NOT NULL DEFAULT FALSE,
	image_url TEXT NOT NULL DEFAULT '/static/assets/images/un.jpeg',
	initial_listed_quantity DOUBLE PRECISION,
	first_listed_at TIMESTAMP,
	first_order_at TIMESTAMP,
	sold_out_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_crops_farmer FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON DELETE CASCADE,
	CONSTRAINT crops_image_url_nonblank CHECK (BTRIM(image_url) <> ''),
	CONSTRAINT chk_crops_quantity CHECK (quantity >= 0),
	CONSTRAINT chk_crops_price CHECK (price_per_unit >= 0),
	CONSTRAINT chk_crops_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
	CONSTRAINT chk_crops_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
	CONSTRAINT chk_crops_location_accuracy CHECK (location_accuracy IS NULL OR location_accuracy > 0)
);
CREATE INDEX IF NOT EXISTS idx_crops_farmer ON crops(farmer_id);
CREATE INDEX IF NOT EXISTS idx_crops_marketplace ON crops(listed_for_sale, quantity, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crops_name ON crops(name);
CREATE INDEX IF NOT EXISTS idx_crops_location ON crops(state, lga);
`); err != nil {
		return fmt.Errorf("crops migration: %w", err)
	}

	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS crop_images (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	crop_id INTEGER NOT NULL,
	image_url TEXT NOT NULL,
	is_primary BOOLEAN NOT NULL DEFAULT FALSE,
	sort_order INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_crop_images_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
	CONSTRAINT chk_crop_images_url CHECK (BTRIM(image_url) <> '')
);
CREATE INDEX IF NOT EXISTS idx_crop_images_crop ON crop_images(crop_id, sort_order);
`); err != nil {
		return fmt.Errorf("crop images migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 3. MARKET ANALYTICS / HISTORY
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS produce_price_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	crop_id INTEGER NOT NULL,
	price_per_unit DOUBLE PRECISION NOT NULL,
	unit TEXT NOT NULL,
	source TEXT NOT NULL DEFAULT 'Agro-Shield',
	observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_price_history_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_price_history_crop_time ON produce_price_history(crop_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS inventory_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	crop_id INTEGER NOT NULL,
	quantity_before DOUBLE PRECISION NOT NULL,
	quantity_change DOUBLE PRECISION NOT NULL,
	quantity_after DOUBLE PRECISION NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_inventory_history_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_inventory_history_crop_time ON inventory_history(crop_id, created_at DESC);

CREATE TABLE IF NOT EXISTS external_market_prices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	produce_type TEXT NOT NULL,
	price_per_unit DOUBLE PRECISION NOT NULL,
	unit TEXT NOT NULL,
	currency TEXT NOT NULL DEFAULT 'NGN',
	provider TEXT NOT NULL,
	market_name TEXT NOT NULL,
	lga TEXT,
	state TEXT,
	country TEXT NOT NULL DEFAULT 'Nigeria',
	collected_at TIMESTAMP NOT NULL,
	imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	source_url TEXT
);
CREATE INDEX IF NOT EXISTS idx_external_prices_produce_market_time ON external_market_prices(produce_type, state, collected_at DESC);

CREATE TABLE IF NOT EXISTS lga_neighbors (
	state TEXT NOT NULL,
	lga TEXT NOT NULL,
	neighbor_lga TEXT NOT NULL,
	PRIMARY KEY (state, lga, neighbor_lga)
);

CREATE TABLE IF NOT EXISTS market_events (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_type TEXT NOT NULL,
	crop_id INTEGER,
	user_id INTEGER,
	session_id TEXT,
	metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_market_events_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
	CONSTRAINT fk_market_events_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_market_events_crop_time ON market_events(crop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_market_events_type_time ON market_events(event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS marketplace_searches (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	search_term TEXT NOT NULL,
	normalized_produce TEXT,
	location TEXT,
	user_id INTEGER,
	session_id TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_marketplace_searches_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_marketplace_searches_term_time ON marketplace_searches(normalized_produce, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_searches_location_time ON marketplace_searches(location, created_at DESC);
`); err != nil {
		return fmt.Errorf("market history migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 4. DIAGNOSIS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS diagnoses (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	farmer_id INTEGER NOT NULL,
	category TEXT NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT '',
	result TEXT NOT NULL,
	image_name TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_diagnoses_farmer FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diagnoses_farmer_time ON diagnoses(farmer_id, created_at DESC);

CREATE TABLE IF NOT EXISTS diagnosis_media (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	diagnosis_id INTEGER NOT NULL,
	media_type TEXT NOT NULL,
	file_name TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_diagnosis_media_diagnosis FOREIGN KEY (diagnosis_id) REFERENCES diagnoses(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diagnosis_media_diagnosis ON diagnosis_media(diagnosis_id);
`); err != nil {
		return fmt.Errorf("diagnosis migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 5. NEGOTIATIONS
	//
	// This is deliberately the unified schema. crop_id is the canonical product
	// reference. There is no product_id/crop_id split.
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS negotiations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	crop_id INTEGER NOT NULL,
	buyer_id INTEGER NOT NULL,
	farmer_id INTEGER NOT NULL,
	quantity DOUBLE PRECISION NOT NULL,
	initial_offer_price NUMERIC(12,2) NOT NULL DEFAULT 0,
	current_offer_price NUMERIC(12,2) NOT NULL DEFAULT 0,
	round_count INTEGER NOT NULL DEFAULT 0,
	max_rounds INTEGER NOT NULL DEFAULT 5,
	status TEXT NOT NULL DEFAULT 'pending',
	expires_at TIMESTAMP,
	accepted_at TIMESTAMP,
	closed_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_negotiations_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
	CONSTRAINT fk_negotiations_buyer FOREIGN KEY (buyer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT fk_negotiations_farmer FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT chk_negotiations_quantity CHECK (quantity > 0),
	CONSTRAINT chk_negotiations_prices CHECK (initial_offer_price >= 0 AND current_offer_price >= 0),
	CONSTRAINT chk_negotiations_rounds CHECK (round_count >= 0 AND max_rounds > 0)
);
CREATE INDEX IF NOT EXISTS idx_negotiations_crop ON negotiations(crop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negotiations_buyer ON negotiations(buyer_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negotiations_farmer ON negotiations(farmer_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negotiations_status_expiry ON negotiations(status, expires_at);
`); err != nil {
		return fmt.Errorf("negotiations migration: %w", err)
	}

	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS negotiation_messages (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	negotiation_id INTEGER NOT NULL,
	sender_id INTEGER NOT NULL,
	message_type TEXT NOT NULL DEFAULT 'offer',
	offer_price DOUBLE PRECISION NOT NULL DEFAULT 0,
	message TEXT NOT NULL DEFAULT '',
	offer_status TEXT NOT NULL DEFAULT 'pending',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_messages_negotiation FOREIGN KEY (negotiation_id) REFERENCES negotiations(id) ON DELETE CASCADE,
	CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT chk_message_type CHECK (message_type IN ('message', 'offer')),
	CONSTRAINT chk_offer_status CHECK (offer_status IN ('none', 'pending', 'accepted', 'rejected'))
);
CREATE INDEX IF NOT EXISTS idx_negotiation_messages_negotiation ON negotiation_messages(negotiation_id, created_at);
`); err != nil {
		return fmt.Errorf("negotiation messages migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 6. CART
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS cart_items (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	buyer_id INTEGER NOT NULL,
	crop_id INTEGER NOT NULL,
	negotiation_id INTEGER NOT NULL,
	quantity DOUBLE PRECISION NOT NULL,
	price_per_unit DOUBLE PRECISION NOT NULL,
	total_price DOUBLE PRECISION NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_cart_items_buyer FOREIGN KEY (buyer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT fk_cart_items_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE RESTRICT,
	CONSTRAINT fk_cart_items_negotiation FOREIGN KEY (negotiation_id) REFERENCES negotiations(id) ON DELETE CASCADE,
	CONSTRAINT chk_cart_items_quantity CHECK (quantity > 0),
	CONSTRAINT chk_cart_items_price CHECK (price_per_unit > 0),
	CONSTRAINT chk_cart_items_total CHECK (total_price > 0)
);
CREATE INDEX IF NOT EXISTS idx_cart_items_buyer ON cart_items(buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cart_items_negotiation ON cart_items(negotiation_id);
`); err != nil {
		return fmt.Errorf("cart migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 7. ORDERS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS orders (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	buyer_id INTEGER NOT NULL,
	crop_id INTEGER NOT NULL,
	quantity DOUBLE PRECISION NOT NULL,
	total_price DOUBLE PRECISION NOT NULL,
	status TEXT NOT NULL DEFAULT 'pending',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT fk_orders_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE RESTRICT,
	CONSTRAINT chk_orders_quantity CHECK (quantity > 0),
	CONSTRAINT chk_orders_total CHECK (total_price >= 0)
);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_time ON orders(buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_crop_time ON orders(crop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_time ON orders(status, created_at DESC);
`); err != nil {
		return fmt.Errorf("orders migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 8. DELIVERIES
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS deliveries (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id INTEGER NOT NULL,
	buyer_id INTEGER NOT NULL,
	farmer_id INTEGER NOT NULL,
	crop_id INTEGER NOT NULL,
	quantity DOUBLE PRECISION NOT NULL,
	delivery_address TEXT NOT NULL,
	lga TEXT,
	state TEXT,
	country TEXT NOT NULL DEFAULT 'Nigeria',
	latitude DOUBLE PRECISION,
	longitude DOUBLE PRECISION,
	status TEXT NOT NULL DEFAULT 'pending',
	courier_name TEXT,
	courier_phone TEXT,
	tracking_number TEXT,
	vehicle_info TEXT,
	scheduled_at TIMESTAMP,
	estimated_arrival TIMESTAMP,
	picked_up_at TIMESTAMP,
	delivered_at TIMESTAMP,
	cancelled_at TIMESTAMP,
	notes TEXT,
	proof_of_delivery TEXT,
	failure_reason TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_deliveries_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
	CONSTRAINT fk_deliveries_buyer FOREIGN KEY (buyer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT fk_deliveries_farmer FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON DELETE RESTRICT,
	CONSTRAINT fk_deliveries_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE RESTRICT,
	CONSTRAINT chk_deliveries_quantity CHECK (quantity > 0),
	CONSTRAINT chk_deliveries_status CHECK (status IN ('pending','confirmed','picked_up','in_transit','delivered','failed','cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_deliveries_order ON deliveries(order_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_buyer_status ON deliveries(buyer_id, status);
CREATE INDEX IF NOT EXISTS idx_deliveries_farmer_status ON deliveries(farmer_id, status);
CREATE INDEX IF NOT EXISTS idx_deliveries_status_created ON deliveries(status, created_at DESC);
`); err != nil {
		return fmt.Errorf("deliveries migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 9. PAYMENTS / WEBHOOKS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS payments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id INTEGER NOT NULL,
	reference VARCHAR(100) NOT NULL UNIQUE,
	transaction_id VARCHAR(100),
	amount NUMERIC(12,2) NOT NULL,
	currency VARCHAR(3) NOT NULL DEFAULT 'NGN',
	status VARCHAR(20) NOT NULL DEFAULT 'pending',
	provider VARCHAR(30) NOT NULL DEFAULT 'flutterwave',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_transaction_id ON payments(transaction_id);

CREATE TABLE IF NOT EXISTS webhook_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	transaction_id VARCHAR(100) NOT NULL,
	event VARCHAR(50) NOT NULL,
	payload JSONB NOT NULL,
	processed_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uq_webhook_event UNIQUE (transaction_id, event)
);
`); err != nil {
		return fmt.Errorf("payments migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 10. NOTIFICATIONS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS notifications (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	message TEXT NOT NULL,
	type TEXT NOT NULL,
	is_read BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read_time ON notifications(user_id, is_read, created_at DESC);
`); err != nil {
		return fmt.Errorf("notifications migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 11. GENERAL CHAT
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS conversations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT,
	type TEXT NOT NULL DEFAULT 'private',
	created_by INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_conversations_creator FOREIGN KEY (created_by) REFERENCES farmers(id) ON DELETE CASCADE,
	CONSTRAINT chk_conversation_type CHECK (type IN ('private','group'))
);

CREATE TABLE IF NOT EXISTS conversation_members (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	conversation_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_conversation_members_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
	CONSTRAINT fk_conversation_members_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE CASCADE,
	CONSTRAINT unique_conversation_member UNIQUE (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members(user_id, conversation_id);

CREATE TABLE IF NOT EXISTS chat_messages (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	conversation_id INTEGER NOT NULL,
	sender_id INTEGER NOT NULL,
	message TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_chat_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
	CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES farmers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation_time ON chat_messages(conversation_id, created_at);
`); err != nil {
		return fmt.Errorf("chat migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 12. FEEDBACK / REVIEWS
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE TABLE IF NOT EXISTS feedback (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,
	farmer_id INTEGER NOT NULL,
	product_id INTEGER,
	rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
	comment TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE CASCADE,
	CONSTRAINT fk_feedback_farmer FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_feedback_farmer_time ON feedback(farmer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_product_time ON feedback(product_id, created_at DESC);
`); err != nil {
		return fmt.Errorf("feedback migration: %w", err)
	}

	// -------------------------------------------------------------------------
	// 13. FINAL SAFETY INDEXES
	// -------------------------------------------------------------------------
	if _, err := db.Exec(`
CREATE INDEX IF NOT EXISTS idx_crops_farmer_listed ON crops(farmer_id, listed_for_sale, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crop_images_primary ON crop_images(crop_id, is_primary, sort_order);
CREATE INDEX IF NOT EXISTS idx_negotiation_messages_sender ON negotiation_messages(sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_status ON orders(buyer_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deliveries_crop_status ON deliveries(crop_id, status);
`); err != nil {
		return fmt.Errorf("final indexes migration: %w", err)
	}

	log.Println("✅ Agro-Shield fresh PostgreSQL schema created successfully")
	return nil
}
