package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
)

// ============================================================
// 1. CONNECT TO POSTGRESQL
//
// Responsibility:
// - Load DATABASE_URL.
// - Connect Agro-Shield to PostgreSQL.
// - Verify that the database is reachable.
// ============================================================

func ConnectDB() (*sql.DB, error) {

	godotenv.Load()

	databaseURL := os.Getenv("DATABASE_URL")

	if databaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is not set")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(); err != nil {
		return nil, err
	}

	log.Println("✅ Connected to PostgreSQL database")

	return db, nil
}

// ============================================================
// 2. RUN DATABASE MIGRATIONS
//
// Responsibility:
// - Create all Agro-Shield database tables.
// - Update older tables when new columns are introduced.
// ============================================================

func RunMigration(db *sql.DB) error {
	marketEventsTable := `
	CREATE TABLE IF NOT EXISTS market_events (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		event_type TEXT NOT NULL,
		crop_id INTEGER,
		user_id INTEGER,
		session_id TEXT,
		metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT fk_market_events_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
		CONSTRAINT fk_market_events_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
	);
	CREATE INDEX IF NOT EXISTS idx_market_events_crop_time ON market_events(crop_id, created_at);
	CREATE INDEX IF NOT EXISTS idx_market_events_type_time ON market_events(event_type, created_at);
	`
	marketplaceSearchesTable := `
	CREATE TABLE IF NOT EXISTS marketplace_searches (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		search_term TEXT NOT NULL,
		normalized_produce TEXT,
		location TEXT,
		user_id INTEGER,
		session_id TEXT,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT fk_marketplace_searches_user FOREIGN KEY (user_id) REFERENCES farmers(id) ON DELETE SET NULL
	);
	CREATE INDEX IF NOT EXISTS idx_marketplace_searches_term_time ON marketplace_searches(normalized_produce, created_at);
	CREATE INDEX IF NOT EXISTS idx_marketplace_searches_location_time ON marketplace_searches(location, created_at);
	`

	// ========================================================
	// 3. FARMERS TABLE
	//
	// Stores all Agro-Shield users.
	// ========================================================

	farmersTable := `
	CREATE TABLE IF NOT EXISTS farmers (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		full_name TEXT NOT NULL,

		phone TEXT NOT NULL UNIQUE,

		email TEXT,

		password_hash TEXT NOT NULL,

		location TEXT NOT NULL,

		role TEXT NOT NULL DEFAULT 'farmer',

		photo_url TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);
	`

	_, err := db.Exec(farmersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers table migrated successfully")

	// ========================================================
	// 4. FARMERS EMAIL COLUMN MIGRATION
	//
	// Makes sure older databases also receive email.
	// ========================================================

	addEmailColumn := `
	ALTER TABLE farmers
	ADD COLUMN IF NOT EXISTS email TEXT;
	`

	_, err = db.Exec(addEmailColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers email column migrated successfully")

	// Pictures are required for every farmer and crop. This also upgrades
	// databases created before the NOT NULL constraints were introduced.
	if _, err = db.Exec(`ALTER TABLE farmers ALTER COLUMN photo_url SET NOT NULL`); err != nil {
		return fmt.Errorf("farmers.photo_url must be populated before migration: %w", err)
	}

	// ========================================================
	// 5. CROPS TABLE
	//
	// Stores agricultural produce listed by farmers.
	// ========================================================

	cropsTable := `
	CREATE TABLE IF NOT EXISTS crops (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		farmer_id INTEGER NOT NULL,

		name TEXT NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		unit TEXT NOT NULL,

		location TEXT NOT NULL,

		price_per_unit DOUBLE PRECISION NOT NULL,

		listed_for_sale BOOLEAN NOT NULL DEFAULT FALSE,

		image_url TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_crops_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(cropsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Crops table migrated successfully")

	lifecycleColumns := `ALTER TABLE crops ADD COLUMN IF NOT EXISTS initial_listed_quantity DOUBLE PRECISION; ALTER TABLE crops ADD COLUMN IF NOT EXISTS first_listed_at TIMESTAMP; ALTER TABLE crops ADD COLUMN IF NOT EXISTS first_order_at TIMESTAMP; ALTER TABLE crops ADD COLUMN IF NOT EXISTS sold_out_at TIMESTAMP; UPDATE crops SET initial_listed_quantity=quantity WHERE initial_listed_quantity IS NULL; UPDATE crops SET first_listed_at=created_at WHERE first_listed_at IS NULL AND listed_for_sale=true;`
	if _, err = db.Exec(lifecycleColumns); err != nil { return err }
	log.Println("✅ Produce listing lifecycle columns migrated successfully")

	if _, err = db.Exec(marketEventsTable); err != nil {
		return err
	}
	log.Println("✅ Market events table migrated successfully")
	if _, err = db.Exec(marketplaceSearchesTable); err != nil {
		return err
	}
	log.Println("✅ Marketplace searches table migrated successfully")

	if _, err = db.Exec(`ALTER TABLE crops ALTER COLUMN image_url SET NOT NULL`); err != nil {
		return fmt.Errorf("crops.image_url must be populated before migration: %w", err)
	}

	// ========================================================
	// 6. DIAGNOSES TABLE
	//
	// Stores AI diagnosis results.
	// ========================================================

	diagnosesTable := `
	CREATE TABLE IF NOT EXISTS diagnoses (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		farmer_id INTEGER NOT NULL,

		image_name TEXT NOT NULL,

		result TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnoses_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnoses table migrated successfully")

	// ========================================================
	// 7. DIAGNOSIS MEDIA TABLE
	//
	// Stores media connected to AI diagnoses.
	// ========================================================

	diagnosisMediaTable := `
	CREATE TABLE IF NOT EXISTS diagnosis_media (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		diagnosis_id INTEGER NOT NULL,

		media_type TEXT NOT NULL,

		file_name TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnosis_media_diagnosis
			FOREIGN KEY (diagnosis_id)
			REFERENCES diagnoses(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosisMediaTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnosis media table migrated successfully")

	// ========================================================
	// 8. ORDERS TABLE
	//
	// Stores purchases made by buyers.
	// ========================================================

	ordersTable := `
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		buyer_id INTEGER NOT NULL,

		crop_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		total_price DOUBLE PRECISION NOT NULL,

		status TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_orders_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_orders_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id)
	);
	`

	_, err = db.Exec(ordersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Orders table migrated successfully")

	// ========================================================
	// 9. NEGOTIATIONS TABLE
	//
	// Stores buyer ↔ farmer negotiations.
	// ========================================================

	negotiationsTable := `
	CREATE TABLE IF NOT EXISTS negotiations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		crop_id INTEGER NOT NULL,

		buyer_id INTEGER NOT NULL,

		farmer_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		status TEXT NOT NULL,

		round_count INTEGER NOT NULL DEFAULT 0,

		max_rounds INTEGER NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		expires_at TIMESTAMP,

		CONSTRAINT fk_negotiations_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_negotiations_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_negotiations_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
	);
	`

	_, err = db.Exec(negotiationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiations table migrated successfully")

	// ========================================================
	// 10. NEGOTIATION MESSAGES TABLE
	//
	// Stores messages and offers inside negotiations.
	//
	// This is DIFFERENT from general chat.
	// ========================================================

	negotiationMessagesTable := `
	CREATE TABLE IF NOT EXISTS negotiation_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		negotiation_id INTEGER NOT NULL,

		sender_id INTEGER NOT NULL,

		message_type TEXT NOT NULL DEFAULT 'offer',

		offer_price DOUBLE PRECISION NOT NULL DEFAULT 0,

		message TEXT NOT NULL DEFAULT '',

		offer_status TEXT NOT NULL DEFAULT 'pending',

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_messages_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id),

		CONSTRAINT chk_message_type
			CHECK (message_type IN ('message', 'offer')),

		CONSTRAINT chk_offer_status
			CHECK (
				offer_status IN (
					'none',
					'pending',
					'accepted',
					'rejected'
				)
			)
	);
	`

	_, err = db.Exec(negotiationMessagesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation messages table migrated successfully")

	// ========================================================
	// 10B. NEGOTIATION MESSAGE TYPE MIGRATION
	//
	// Adds message_type to older databases.
	// ========================================================

	addMessageTypeColumn := `
	ALTER TABLE negotiation_messages
	ADD COLUMN IF NOT EXISTS message_type TEXT NOT NULL DEFAULT 'offer';
	`

	_, err = db.Exec(addMessageTypeColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation message type column migrated successfully")

	// ========================================================
	// 10C. NEGOTIATION OFFER STATUS MIGRATION
	//
	// Adds offer_status to older databases.
	// ========================================================

	addOfferStatusColumn := `
	ALTER TABLE negotiation_messages
	ADD COLUMN IF NOT EXISTS offer_status TEXT NOT NULL DEFAULT 'pending';
	`

	_, err = db.Exec(addOfferStatusColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation offer status column migrated successfully")

	// ========================================================
	// 11. CART ITEMS TABLE
	//
	// Stores accepted negotiation deals before checkout.
	// ========================================================

	cartItemsTable := `
	CREATE TABLE IF NOT EXISTS cart_items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		buyer_id INTEGER NOT NULL,

		crop_id INTEGER NOT NULL,

		negotiation_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		price_per_unit DOUBLE PRECISION NOT NULL,

		total_price DOUBLE PRECISION NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_cart_items_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_cart_items_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_cart_items_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT chk_cart_items_quantity
			CHECK (quantity > 0),

		CONSTRAINT chk_cart_items_price
			CHECK (price_per_unit > 0),

		CONSTRAINT chk_cart_items_total
			CHECK (total_price > 0)
	);
	`

	_, err = db.Exec(cartItemsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Cart items table migrated successfully")

	// ========================================================
	// 12. NOTIFICATIONS TABLE
	//
	// Stores notifications for Agro-Shield users.
	// ========================================================

	notificationsTable := `
	CREATE TABLE IF NOT EXISTS notifications (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		user_id INTEGER NOT NULL,

		title TEXT NOT NULL,

		message TEXT NOT NULL,

		type TEXT NOT NULL,

		is_read BOOLEAN NOT NULL DEFAULT FALSE,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_notifications_user
			FOREIGN KEY (user_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(notificationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Notifications table migrated successfully")

	// ========================================================
	// 13. CONVERSATIONS TABLE
	//
	// Represents a general Agro-Shield chat room.
	//
	// private:
	//   User ↔ User
	//
	// group:
	//   User ↔ User ↔ User ↔ ...
	//
	// IMPORTANT:
	// This is NOT a negotiation.
	// ========================================================

	conversationsTable := `
	CREATE TABLE IF NOT EXISTS conversations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		name TEXT,

		type TEXT NOT NULL DEFAULT 'private',

		created_by INTEGER NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_conversations_creator
			FOREIGN KEY (created_by)
			REFERENCES farmers(id)
			ON DELETE CASCADE,

		CONSTRAINT chk_conversation_type
			CHECK (type IN ('private', 'group'))
	);
	`

	_, err = db.Exec(conversationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Conversations table migrated successfully")

	// ========================================================
	// 14. CONVERSATION MEMBERS TABLE
	//
	// Connects users to conversations.
	//
	// This table makes group chat possible.
	//
	// Example:
	//
	// Maize Farmers Association
	//        |
	//        +-- James
	//        +-- Peter
	//        +-- Grace
	//        +-- Michael
	// ========================================================

	conversationMembersTable := `
	CREATE TABLE IF NOT EXISTS conversation_members (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		conversation_id INTEGER NOT NULL,

		user_id INTEGER NOT NULL,

		joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_conversation_members_conversation
			FOREIGN KEY (conversation_id)
			REFERENCES conversations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_conversation_members_user
			FOREIGN KEY (user_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE,

		CONSTRAINT unique_conversation_member
			UNIQUE (conversation_id, user_id)
	);
	`

	_, err = db.Exec(conversationMembersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Conversation members table migrated successfully")

	// ========================================================
	// 15. CHAT MESSAGES TABLE
	//
	// Stores normal Agro-Shield chat messages.
	//
	// This is different from negotiation_messages.
	// ========================================================

	chatMessagesTable := `
	CREATE TABLE IF NOT EXISTS chat_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		conversation_id INTEGER NOT NULL,

		sender_id INTEGER NOT NULL,

		message TEXT NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_chat_messages_conversation
			FOREIGN KEY (conversation_id)
			REFERENCES conversations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_chat_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(chatMessagesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Chat messages table migrated successfully")

	// ========================================================
	// 16. DATABASE MIGRATION COMPLETE
	// ========================================================

	log.Println("✅ All database migrations completed successfully")

	return nil
}
